openapi: "3.0.1"
info:
  title: "Maxfrise API v2"
  version: "1.0"
paths:
  /initlease:
    post:
      summary: "Service to initialize the lease"
      responses:
        '200':
          description: "Successful response"
      x-amazon-apigateway-integration:
        uri: "${initLeaseLambdaArn}"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"
  /collectpayment:
    post:
      summary: "Service to collect payments"
      responses:
        '200':
          description: "Successful response"
      x-amazon-apigateway-integration:
        uri: "${paymentCollectorLambdaArn}"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"
  /createhouse:
    post:
      summary: "Service to create houses"
      responses:
        '200':
          description: "Successful response"
      x-amazon-apigateway-integration:
        uri: "${createHouseLambdaArn}"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"
  /gethouses:
    get:
      summary: "Service to get houses"
      responses:
        '200':
          description: "Successful response"
      x-amazon-apigateway-integration:
        uri: "${getHousesLambdaArn}"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"
  /houseoverview:
    get:
      summary: "Function to get the house overview"
      responses:
        '200':
          description: "Successful response"
      x-amazon-apigateway-integration:
        uri: "${houseOverviewLambdaArn}"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"
