openapi: "3.0.1"
info:
  title: "Maxfrise API v2"
  version: "1.0"
paths:
  /initLease:
    post:
      summary: "Service to initialize the lease"
      responses:
        '200':
          description: "Successful response"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/${initLeaseLambdaArn}/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"
  /paymentCollector:
    post:
      summary: "Service to collect payments"
      responses:
        '200':
          description: "Successful response"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/${paymentCollectorLambdaArn}/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"
  /createHouse:
    post:
      summary: "Service to create houses"
      responses:
        '200':
          description: "Successful response"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/${createHouseLambdaArn}/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"
  /getHouses:
    get:
      summary: "Service to get houses"
      responses:
        '200':
          description: "Successful response"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/${getHousesLambdaArn}/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"
  /houseOverview:
    get:
      summary: "Function to get the house overview"
      responses:
        '200':
          description: "Successful response"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/${houseOverviewLambdaArn}/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"
