name: Tests
run-name: Validate
on:
  pull_request:
jobs:
  tests:
    name: Unit tests and lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Get node version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm
      - name: Install correct node version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: false
              args: [--frozen-lockfile]
      - name: Test
        run: pnpm run --parallel -r test